### ISSUE TITLE
Problème avec l'échappement de l'esperluette.

### ISSUE THREAD

**Issue by aquemy** [kanboard/plugin-mattermost#3]
Bonjour,

Dans les logs, j'observe une refus de la part de Mattermost:

```
[2016-07-16 11:45:52] [error] HttpClient: request failed
[2016-07-16 11:45:52] [debug] HttpClient: url=https://[mattermost_url]/hooks/[token]
```

J'ai donc essayé avec curl la requête et il s'avère que l'esperluette n'est pas correctement échappée dans le payload:

```
HTTP/1.1 307 Temporary Redirect
Server: nginx
Date: Sat, 16 Jul 2016 12:50:21 GMT
Content-Type: text/plain; charset=utf-8
Location: /error?title=Mattermost+needs+your+help%3A&message=Unable+to+parse+incoming+data&details=&link=%2F&linkmessage=Go+back+to+Mattermost
```

La notification passe lorsque je remplace l'esperluette par %26:

Refusée : /?controller=TaskViewController**&**action=show**&**task_id=3**&**project_id=1
Acceptée : /?controller=TaskViewController**%26**action=show**%26**task_id=3**%26**project_id=1

Je ne sais pas si cela vient de ma configuration de PHP ou du plugin.

**Comment by aquemy** [comment]
A priori, cela viendrait de la configuration de nginx puisque lorsque je ne passe pas par le reverse-proxy (mattermost etant heberge sur le meme serveur) cela fonctionne. Je ne pense pas que l'on puisse faire grand chose du cote de Kanboard pour cela.

Des que j'ai le temps je regarde du cote de nginx. Cela vaudra probablement le coup de l'ajouter a la documentation s'il ne s'agit que d'un probleme de configuration.

**Comment by fguillot** [comment]
Je viens de tester avec Mattermost 3.2.0 et Kanboard avec url rewriting activé/désactivé et pour moi ça fonctionne sans problème.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
