### ISSUE TITLE
Notify user

### ISSUE THREAD

**Issue by ohlookemus** [kanboard/plugin-mattermost#4]
On the mattermost integration page it says you can notify a channel/group/user,

How does group/user actually work since looking at the source (I don't have a strong grasp of PHP so forgive me), it doesn't actually seem possible.

**Comment by fguillot** [comment]
This plugin doesn't send notifications to a single user or a group, only to a channel.

Incoming Mattermost webhooks don't even seems to support direct message to a user, only mentions.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
